apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rules-storage
    app.kubernetes.io/instance: example-rules-objstore
    app.kubernetes.io/name: rules-objstore
    app.kubernetes.io/version: main-2022-01-19-8650540
  name: example-rules-objstore
  namespace: observatroium
